osx_image: xcode10
language: objective-c
cache:
  - bundler
install:
  - bundle install
script:
  - bundle exec fastlane ci
before_install:
  - git config --global user.name "Travis CI"
  - git config --global user.email "travis@travis-ci.org"
  - echo -e "machine github.com\n login $HOMEASSISTANT_CERTIFICATE_USER\n password $HOMEASSISTANT_GITHUB_API_TOKEN" >> ~/.netrc
after_success:
  - sleep 6
rvm: 2.4.2
