name: Download Localized Strings
on:
  workflow_dispatch:

jobs:
  update_strings:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Gems
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3

      - name: Install Pods
        run: bundle exec pod install --repo-update

      - name: Download from Lokalise
        run: bundle exec fastlane update_strings
        env:
          HOMEASSISTANT_LOKALIZE_PROJECT_ID: ${{ secrets.HOMEASSISTANT_LOKALIZE_PROJECT_ID }}
          HOMEASSISTANT_LOKALIZE_TOKEN: ${{ secrets.HOMEASSISTANT_LOKALIZE_TOKEN }}
      - name: Commit changes
        run: |
          git diff --exit-code HomeAssistant/Resources/en.lproj/Localizable.strings >/dev/null
          git checkout -- HomeAssistant.xcodeproj/project.pbxproj
          git config --global user.name 'Home Assistant Bot'
          git config --global user.email 'hello@home-assistant.io'
          git commit -am "Update Localized Strings"
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
