name: Push CI

on:
  pull_request:
    paths:
      - 'Sources/PushServer/**'
  push:
    branches:
      - master
    paths:
      - 'Sources/PushServer/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: fwal/setup-swift@7ca6abe6b3b0e8b5421b88be48feee39cbf52c6a  # v2.4.0
        with:
          swift-version: "5.8"
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3  # v6.0.0
      - name: Run Tests
        run: swift test
        working-directory: Sources/PushServer
