name: Push Deploy

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'The tag to give the image'
        required: true
        type: string

concurrency:
  group: '${{ github.workflow }}'
  cancel-in-progress: true

jobs:
  deploy:
    name: Deploy image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9  # v3.7.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@10e90e3645eae34f1e60eeb005ba3a3d33f178e8  # v6.19.2
        with:
          context: ./Sources/PushServer
          push: true
          tags: "ghcr.io/${{ github.repository_owner }}/ios-pushserver:${{ github.event.inputs.tag }}"
